// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAllEvents = `-- name: GetAllEvents :many
SELECT id, name, starts_at
FROM events
ORDER BY starts_at ASC
`

type GetAllEventsRow struct {
	ID       uuid.UUID
	Name     string
	StartsAt time.Time
}

func (q *Queries) GetAllEvents(ctx context.Context) ([]GetAllEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEventsRow
	for rows.Next() {
		var i GetAllEventsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.StartsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventById = `-- name: GetEventById :one
SELECT id, name, starts_at
FROM events
WHERE id = $1
`

type GetEventByIdRow struct {
	ID       uuid.UUID
	Name     string
	StartsAt time.Time
}

func (q *Queries) GetEventById(ctx context.Context, id uuid.UUID) (GetEventByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getEventById, id)
	var i GetEventByIdRow
	err := row.Scan(&i.ID, &i.Name, &i.StartsAt)
	return i, err
}

const getFutureEvents = `-- name: GetFutureEvents :many
SELECT id, name, starts_at
FROM events
WHERE starts_at >= NOW()
ORDER BY starts_at ASC
`

type GetFutureEventsRow struct {
	ID       uuid.UUID
	Name     string
	StartsAt time.Time
}

func (q *Queries) GetFutureEvents(ctx context.Context) ([]GetFutureEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFutureEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFutureEventsRow
	for rows.Next() {
		var i GetFutureEventsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.StartsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
