// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Class struct {
	ID   uuid.UUID
	Code string
}

type Event struct {
	ID       uuid.UUID
	SeasonID uuid.UUID
	Name     string
	StartsAt time.Time
}

type EventClass struct {
	ID      uuid.UUID
	EventID uuid.UUID
	ClassID uuid.UUID
}

type Pick struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	EventClassID uuid.UUID
	Wager        int32
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type PickPosition struct {
	ID       uuid.UUID
	PickID   uuid.UUID
	RiderID  uuid.UUID
	Position int32
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Result struct {
	EventClassID uuid.UUID
	RiderID      uuid.UUID
	Position     int32
}

type Rider struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	ClassID   uuid.NullUUID
}

type Role struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

type Season struct {
	ID       uuid.UUID
	Name     string
	StartsAt time.Time
	EndsAt   time.Time
	IsActive bool
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	Balance      int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserRole struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}
